-- [05. 5월 식품들의 총매출 조회하기]

# submitted code
SELECT p.PRODUCT_ID
     , p.PRODUCT_NAME
     , SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
INNER JOIN FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(o.PRODUCE_DATE) = '2022' 
  AND MONTH(o.PRODUCE_DATE) = '5'
GROUP BY 1, 2
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
