-- [08. 오랜 기간 보호한 동물(1)]

# submitted code - version 1
SELECT i.NAME
     , i.DATETIME
FROM ANIMAL_INS i
LEFT JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE o.DATETIME IS NULL
ORDER BY (SELECT DATEDIFF(MAX(DATETIME), i.DATETIME) FROM ANIMAL_INS) DESC
LIMIT 3;

# submitted code - version 2
SELECT NAME
     , DATETIME
FROM (SELECT i.NAME
           , i.DATETIME
           , ROW_NUMBER() OVER (ORDER BY (SELECT DATEDIFF(MAX(DATETIME), i.DATETIME) FROM ANIMAL_INS) DESC) AS cnt_date
FROM ANIMAL_INS i
LEFT JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE o.DATETIME IS NULL) t
WHERE cnt_date <= 3;
