-- [10. 상품별 오프라인 매출 구하기]

# submitted code
SELECT p.PRODUCT_CODE
     , SUM(p.price * o.SALES_AMOUNT) AS SALES
FROM PRODUCT p
INNER JOIN OFFLINE_SALE o ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY 1
ORDER BY SALES DESC, p.PRODUCT_CODE;