-- [17. 카테고리 별 상품 개수 구하기]

# submitted code - version 1
SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY
     , COUNT(PRODUCT_ID) AS PRODUCTS
FROM PRODUCT
GROUP BY 1
ORDER BY PRODUCT_CODE;

# submitted code - version 2
SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY
     , SUM(COUNT(PRODUCT_ID)) OVER (PARTITION BY LEFT(PRODUCT_CODE, 2) ORDER BY PRODUCT_CODE) AS PRODUCTS
FROM PRODUCT
GROUP BY 1;