-- [19. 자동차 대여 기록에서 대여정보 구분하기]

# submitted code
SELECT HISTORY_ID
     , CAR_ID
     , DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE
     , DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE
     , IF(DATE_ADD(START_DATE, INTERVAL 29 DAY) > END_DATE, '단기 대여', '장기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-09-01'
  AND START_DATE < '2022-10-01'
ORDER BY 1 DESC;
