-- [21. 성분으로 구분한 아이스크림 총 주문량]

# submitted code
SELECT INGREDIENT_TYPE
     , SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF h
INNER JOIN ICECREAM_INFO i ON h.FLAVOR = i.FLAVOR 
GROUP BY 1
ORDER BY 2;