-- [22. 저자별 카테고리별 매출액 집계하기]

# submitted code
SELECT a.AUTHOR_ID 
     , AUTHOR_NAME
     , CATEGORY
     , SUM(SALES * PRICE) AS TOTAL_SALES
FROM book b
INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
INNER JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE SALES_DATE >= '2022-01-01'
  AND SALES_DATE <'2022-02-01' 
GROUP BY 1, 2, 3
ORDER BY 1, 3 DESC;
