-- [24. 년도별, 월별, 성별별 상품 구매 회원 수 구하기]

# submitted code - version 1
SELECT YEAR(SALES_DATE) AS YEAR
     , MONTH(SALES_DATE) AS MONTH
     , GENDER 
     , COUNT(DISTINCT s.USER_ID) AS USERS
FROM ONLINE_SALE s
INNER JOIN USER_INFO i ON s.USER_ID = i.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;

# submitted code - version 2
SELECT DATE_FORMAT(SALES_DATE, '%Y') AS YEAR
     , DATE_FORMAT(SALES_DATE, '%m') AS MONTH
     , GENDER 
     , COUNT(DISTINCT s.USER_ID) AS USERS
FROM ONLINE_SALE s
INNER JOIN USER_INFO i ON s.USER_ID = i.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;
