-- [27. 카테고리별 도서 판매량 집계하기]

# submitted code
SELECT CATEGORY
     , SUM(SALES) AS TOTAL_SALES
FROM BOOK b
INNER JOIN BOOK_SALES bs ON b.BOOK_ID = bs.BOOK_ID
WHERE SALES_DATE >= '2022-01-01'
  AND SALES_DATE < '2022-02-01'
GROUP BY 1
ORDER BY 1;