-- [30. 서울에 위치한 식당 목록 출력하기]

# submitted code
SELECT ri.REST_ID
     , REST_NAME
     , FOOD_TYPE
     , FAVORITES
     , ADDRESS
     , ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO ri
INNER JOIN REST_REVIEW rr ON ri.REST_ID = rr.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY 1
ORDER BY SCORE DESC, FAVORITES DESC; 